### ISSUE TITLE
How do I add duckyscripts

### ISSUE THREAD

**Issue by YepJustAGamer** [mame82/P4wnP1#103]
I have been trying to figure this out. I have looked on the sd card but I can't find it?

**Comment by 3FF-53C-Member-DalmAsian** [comment]
you must be in a Linux computer to see the partition on the SD card that has all the system folders and it will be under home folder then the p4wnp1 folder then you'll see the duckyscript folder.

**Comment by 3FF-53C-Member-DalmAsian** [comment]
@YepJustAGamer you must be in a Linux computer to see the partition on the SD card that has all the system folders and it will be under home folder then the p4wnp1 folder then you'll see the duckyscript folder.

**Comment by Hugand** [comment]
and how can I run a ducky script after encoding it with the duckyencoder?

**Comment by 3FF-53C-Member-DalmAsian** [comment]
useing the backdoor payload and  using the SendDuckyScript command

**Comment by Hugand** [comment]
ok

**Comment by mame82** [comment]
This was already answered in other issues.
