### ISSUE TITLE
Hakin9 tutorial doesn't work

### ISSUE THREAD

**Issue by MJGames** [mame82/P4wnP1#115]
Hi, the payload Hakin9 tutorila doen't work. Always it waiting for the drive, but the drive is mounted. I use Win7.

**Comment by mame82** [comment]
What's the name of the thumb drive ?

**Comment by mame82** [comment]
Please reopen if the issue remains

**Comment by bpartin2009** [comment]
I see the same issue. Always wait on drive but it is mounted to E: drive as name "HAKIN9"

**Comment by bpartin2009** [comment]
Windows 10

**Comment by bpartin2009** [comment]
PS C:\Users\1111633> $drive=Get-Volume -FileSystemLabel "HAKIN9" -ErrorAction Stop
Get-Volume : Invalid property
At line:1 char:8
+ $drive=Get-Volume -FileSystemLabel "HAKIN9" -ErrorAction Stop
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (MSFT_Volume:ROOT/Microsoft/...age/MSFT_Volume) [Get-Volume], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041031,Get-Volume

**Comment by bpartin2009** [comment]
So apparently I wasn't signed into said computer as sys admin or root user. I for so this to work, sign on as sys admin, use an OTG cable that can transmit data, and I had to add OTG=false on line 116 of /P4wnP1/boot/boot_P4wnP1 file after the hostmode is checked. Still, all in all, really cool project. I will see if I can't create addiontional functionality. "The world is my oyster"
