### ISSUE TITLE
Only hid mouse works

### ISSUE THREAD

**Issue by 99bit** [mame82/P4wnP1#117]
First of all i installed p4wnp1 by wifi adapter as i write script that run ./install.sh after connecting internet 
After 20 min suddenly screen turned black 
Than i tried every payload but only hid_mouse works other payload not works.

**Comment by gonebad1222** [comment]
A) what screen turned black? the computer screen or the HDMI output?
B) I am running some diagnostics on the HID itself. Swiftb0y can give some insight aswell. I believe it has to do with some of windows updates that have been coming up.
C) Let us know how much coding experience you have :) 
Thanks!
-g0n3b4d

**Comment by 99bit** [comment]
yes screen turned black

**Comment by 99bit** [comment]
HDMI output screen turned black

**Comment by 99bit** [comment]
i Don't have more experience still studying in school

**Comment by mame82** [comment]
The console screen of Pi turns black after some minutes without interaction (there isn't direct interaction when a payload is running). This seems to be some energy saving feature, I haven't done research on how to disable this feature. Suggestions are welcome

**Comment by 99bit** [comment]
thxx now it works perfect 😉😉

**Comment by mame82** [comment]
Nice
