### ISSUE TITLE
Win10_LockPicker no Hash possible when the Username has a space

### ISSUE THREAD

**Issue by pixelwasser** [mame82/P4wnP1#121]
Hello,

I have found maybe the next issue. Currently it seems that the Win10_LockPicker payload is only able to collect hashes from single user Name like "DemoUser" if there is a space in the Username like "Demo User" the script tries to collect the hash from "Demo" which doesn't exist on the machine.

Sincerley
Jan

**Comment by pixelwasser** [comment]
Target was a Windows 10 1607

**Comment by Swiftb0y** [comment]
Even though you explained your issue very clearly, I fear mame is the only one that can help you. So be patient for a view days and you'll probably get a good answer.

**Comment by mame82** [comment]
The root cause which allowed this payliad to work was fixed with KB4041691. So I'll give no further support on this, but a writeup is on the way
