### ISSUE TITLE
windows 10 lock screen hash problem 

### ISSUE THREAD

**Issue by gamahawk97** [mame82/P4wnP1#122]
hi 
i installed P4wnp1 on raspberry pi zero w.... when i boot pi i see error. 
 what is the problems ? where am i wrong?
problems in picture;

![whatsapp image 2017-09-26 at 21 29 23](https://user-images.githubusercontent.com/25270755/30877283-e0473eb6-a301-11e7-9435-75c7b115d2c7.jpeg)

thanks for helping now :)

**Comment by mame82** [comment]
What's the output of `uname -r` ?

**Comment by gamahawk97** [comment]
the output is 4.9.51+

**Comment by mame82** [comment]
Nice, please connect P4wnP1 to internet again and run
```
sudo apt-get update && sudo apt-get -y upgrade
```

This should hopefully upgrade livssl to 1.1 which is missing on your installation

**Comment by gamahawk97** [comment]
ok i  will trying but i dont connect  internet ip addr is always seen 172.24.0.1 how can i fix this?
and thanks a lot for helping :)

**Comment by mame82** [comment]
Use the WiFi_client options from the network_only payload, to connect to a give WiFi or follow this tutorial:

https://youtu.be/QEWaIoal5qU

**Comment by gamahawk97** [comment]
i solved all problems(started from the beginning) it works perfect :D . and your tutorial is very  helpful thanks a lot again ...

**Comment by Swiftb0y** [comment]
you should close it then and ill add an entry to the wiki
