### ISSUE TITLE
Question: Are there any consequences/side effects of renaming P4wnP1 WiFi-settings? 

### ISSUE THREAD

**Issue by abdullah-K** [mame82/P4wnP1#123]
I was wondering if anything "bad" would happen if I were to change the WiFi Access Point name/password (name & psk). I'd like to give it a more innocent-sounding name, not something suspicious like "P4wnP1", haha.
Also, can I do the same for the SSH IP address? Is there a reason the developers chose "172.24.0.1"?
By change, I mean from the setup.cfg file...
![p4wnp1_setup](https://user-images.githubusercontent.com/21252681/30942089-143e5002-a3a6-11e7-8b09-3020a7ce7e0e.png)

**Comment by jcstill** [comment]
There shouldn't be any negative side effects.
Unless you change it to be a hidden aside and forget the SSID.

There is, however, a problem in #110 issue. You shouldn't have any problems though.

**Comment by abdullah-K** [comment]
Thanks @jcstill! Thanks for helping develop this awesome pen-testing tool! It's fun to mess around with 😁
