### ISSUE TITLE
led_blink not possible from ssh session

### ISSUE THREAD

**Issue by Swiftb0y** [mame82/P4wnP1#129]
I was playing around with the P4wnP1 backdoor and noticed that led_blink doesn't work because /tmp/blink_count is owned by root. I wasn't all to test out if that's due to some old way of setting the led in the payload or due to a missing chown in the boot process.

**Comment by mame82** [comment]
Can you check file permissions, because this was fixed here:

https://github.com/mame82/P4wnP1/commit/d0c0e615b20d8ca2aa73380928fb9bd382508b2a

**Comment by Swiftb0y** [comment]
Sorry my Bad. I cloned from my own outdated fork.
