### ISSUE TITLE
P4WnP1 startup script failed to load. 

### ISSUE THREAD

**Issue by E-T-A** [mame82/P4wnP1#136]
Pi Zero W - 16GB - Raspbian Jessie Lite
apt-get update 
apt-get upgrade
apt-get install git

Followed your instructions to install from github and the installer completes without any errors 
"If you got here without any errors... yadada.... RESTART NOW." 

After a restart the PI will boot, but there is a big red FAILED besides the startup script being launched.

**Comment by mame82** [comment]
Please try on a clean Stretch image

**Comment by E-T-A** [comment]
Stretch lite worked a treat! 

Disregard issue request.

Cheers!
