### ISSUE TITLE
Pi Zero as an bootable USB-Drive

### ISSUE THREAD

**Issue by noemu** [mame82/P4wnP1#137]
Would it be possible to boot the Pi as an USB-Drive with a Linux-Distro that just replace the windows seth.exe with the cmd.exe ?

**Comment by mame82** [comment]
It is planned to refine the USB implementation to support CD-Rom emulation. Anyway, I doubt P4wnP1 is able to initialize the USB stack fast enough to get detected as CD drive by BIOS. It is likely that this only could be accomplished by pausing boot (BIOS menu).

Considering your use case: If USB CD-Rom support is introduced, it should be possible to mount ISOs. But I won't provide them with the project. Everybody owning a license is free to use Konboot or similar things, but I don't provide 3rd party ISOs.
