### ISSUE TITLE
Can't use USB Mass Storage

### ISSUE THREAD

**Issue by Hugand** [mame82/P4wnP1#146]
I've already fresh installed P4wnP1 3 times but when I run a payload that enables it, like the hakin9_tutorial one, the drive simply doesn't show.

**Comment by mame82** [comment]
Did you get any details from device manager

**Comment by Hugand** [comment]
I didnt see that. When I get home I can give more information about it.

**Comment by Hugand** [comment]
Everything looks normal, the computer recognizes the pi but doesn't let me save things in it. Here is a screenshot of how it shows on my PC.
![captusetsrar](https://user-images.githubusercontent.com/24555587/31686813-45eb1bce-b37f-11e7-89c0-697d66aa0dbe.PNG)

**Comment by Swiftb0y** [comment]
Stupid question:
Have you tried another cable?

**Comment by Hugand** [comment]
yes

**Comment by Swiftb0y** [comment]
Could you post a screenshot from the device manager and disk utility?

**Comment by Hugand** [comment]
ok

**Comment by Hugand** [comment]
![dispgest](https://user-images.githubusercontent.com/24555587/31688408-2ca3fbb8-b384-11e7-9d04-4421260de1c5.PNG)
![diskutil](https://user-images.githubusercontent.com/24555587/31688416-30aec346-b384-11e7-83f2-729c85d2ae1d.PNG)

**Comment by Swiftb0y** [comment]
Sorry man, no Idea. Could you post the output from `sudo journalctl-u P4wnP1.service`?

**Comment by Hugand** [comment]
-- Logs begin at Thu 2016-11-03 17:16:43 UTC, end at Mon 2017-10-16 22:38:23 UTC. --
Oct 16 22:37:14 MAME82-P4WNP1 systemd[1]: Starting P4wnP1 Startup Service...
Oct 16 22:37:14 MAME82-P4WNP1 bash[171]: =================================== P4wnP1 startup ===========================================
Oct 16 22:37:14 MAME82-P4WNP1 bash[171]: P4wnP1: Init LED control...
Oct 16 22:37:14 MAME82-P4WNP1 bash[171]: P4wnP1: Loading config ...
Oct 16 22:37:15 MAME82-P4WNP1 bash[171]: open: No such file or directory
Oct 16 22:37:16 MAME82-P4WNP1 bash[171]: P4wnP1: Initializing USB gadget ...
Oct 16 22:37:16 MAME82-P4WNP1 bash[171]: /home/pi/P4wnP1/boot/init_usb.sh: line 142: echo: write error: No such file or directory
Oct 16 22:37:17 MAME82-P4WNP1 bash[171]: crw------- 1 root root 242, 0 Oct 16 22:37 /dev/hidg0
Oct 16 22:37:17 MAME82-P4WNP1 bash[171]: crw------- 1 root root 242, 1 Oct 16 22:37 /dev/hidg1
Oct 16 22:37:17 MAME82-P4WNP1 bash[171]: crw------- 1 root root 242, 0 Oct 16 22:37 /dev/hidg0
Oct 16 22:37:17 MAME82-P4WNP1 bash[171]: crw------- 1 root root 242, 1 Oct 16 22:37 /dev/hidg1
Oct 16 22:37:17 MAME82-P4WNP1 bash[171]: P4wnP1: Checking for WiFi capabilities ...
Oct 16 22:37:18 MAME82-P4WNP1 bash[171]: P4wnP1: Seems WiFi module is present !
Oct 16 22:37:19 MAME82-P4WNP1 dnsmasq[259]: started, version 2.76 DNS disabled
Oct 16 22:37:19 MAME82-P4WNP1 dnsmasq[259]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Oct 16 22:37:19 MAME82-P4WNP1 dnsmasq-dhcp[259]: DHCP, IP range 172.24.0.2 -- 172.24.0.100, lease time 5m
Oct 16 22:37:19 MAME82-P4WNP1 dnsmasq-dhcp[259]: DHCP, sockets bound exclusively to interface wlan0
Oct 16 22:37:19 MAME82-P4WNP1 bash[171]: USB OTG off, going on with P4wnP1 boot
Oct 16 22:37:19 MAME82-P4WNP1 bash[171]: P4wnP1: ... USB gadget initialized
Oct 16 22:37:19 MAME82-P4WNP1 bash[171]: P4wnP1: Initializing Ethernet over USB...
Oct 16 22:37:19 MAME82-P4WNP1 bash[171]: CDC ECM or RNDIS active. Check which interface has to be used via Link detection
Oct 16 22:37:19 MAME82-P4WNP1 bash[171]: .Link detected on usb0
Oct 16 22:37:19 MAME82-P4WNP1 systemd[1]: Started P4wnP1 Startup Service.
Oct 16 22:37:19 MAME82-P4WNP1 bash[171]: Waiting for HID keyboard to be usable...
Oct 16 22:37:21 MAME82-P4WNP1 bash[171]: 0
Oct 16 22:37:22 MAME82-P4WNP1 bash[171]: P4wnP1: Creating DHCP configuration for Ethernet over USB...
Oct 16 22:37:23 MAME82-P4WNP1 dnsmasq[368]: started, version 2.76 DNS disabled
Oct 16 22:37:23 MAME82-P4WNP1 dnsmasq[368]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Oct 16 22:37:23 MAME82-P4WNP1 dnsmasq-dhcp[368]: DHCP, IP range 172.16.0.2 -- 172.16.0.2, lease time 5m
Oct 16 22:37:23 MAME82-P4WNP1 dnsmasq-dhcp[368]: DHCP, sockets bound exclusively to interface usb0

**Comment by Hugand** [comment]
for what I've seen I dont have the USB_STORAGE/image.bin on the pi as I saw from "Oct 16 22:37:16 MAME82-P4WNP1 bash[171]: /home/pi/P4wnP1/boot/init_usb.sh: line 142: echo: write error: No such file or directory"

**Comment by Swiftb0y** [comment]
And there you have your Solution: run the lines in the p4wnp1 installer again that go start with something like `dd if=/dev/zero ...` in the P4wnP1 same location as the installer and see if that fixes it.

**Comment by Hugand** [comment]
Ok, thanks!

**Comment by Hugand** [comment]
It works! Thanks for the help!
