### ISSUE TITLE
Payload difference and Command questions..?

### ISSUE THREAD

**Issue by Braandn** [mame82/P4wnP1#155]
What is the difference between HID-Backdoor and HID-Backdoor-Remote and where could i change the commands for example "FireStage1" to "start" or others?

Thanks

**Comment by Swiftb0y** [comment]
The remote variant uses AutoSSH to provide a reverse ssh shell which requires internet access, a properly configured server and a correct setup.cfg/hid_backdoor_remote.txt

There is no proper way to change the names of the commands but you can try editing hidtools/backdoor/P4wnP1.py from `def do_FireStage1` to `do_start`. This will break the help menu and might not work so be careful.

**Comment by Swiftb0y** [comment]
PS. Don't forget the the `def` before do_start (`def do_start`)
