### ISSUE TITLE
How to change Access Point name and password?

### ISSUE THREAD

**Issue by abhbxv** [mame82/P4wnP1#156]
Hi, sir
I started working P4wnP1 on raspberry pi zero w.
I want to change the Access Point name and password, but it can't .
I type $nano setup.cfg and change the name and password.
and reboot it.
it's still show the P4wnP1 Access Point name, not my change name.
can I ask what's step whick I wrong?
thank you.

**Comment by hahnstep** [comment]
Hi look in the payloads , each payload can have his one configuration for network and other stuff.
ich hope it helps
