### ISSUE TITLE
Win10 Pick Locker no longer working?

### ISSUE THREAD

**Issue by liyun-li** [mame82/P4wnP1#158]
Hey! I tested the Win10_PickLocker payload in a locked Windows laptop (with user logged in). Pi was able to collect the hash but the login wasn't behaving correctly (my keyboard language is correct):
1) The password field is not filled;
2) Windows seemed to have logged in but went back to lock screen after.

Also there's a there's a typo in Win10 payload (cacth->catch)

**Comment by mame82** [comment]
Reported to Microsoft and patched with KB4041691.

P4wnP1 was used for testing by Microsoft.

Details here: https://github.com/mame82/P4wnP1/blob/master/writeup_lockpicker.md

**Comment by mr0Ot** [comment]
Cool the rest of it works not.
tell me please why do not remove this script?
whe it not works what do it in this script?

i understand not what you do.
the script and all the payloads works not.
tell me why i install this on a PI?

sorry i found this is a joke!

**Comment by Swiftb0y** [comment]
Please read [the wiki](http://p4wnp1.readthedocs.io/en/latest/Troubleshooting/) and provide debugging output.
