### ISSUE TITLE
(Feature Request) New Payload

### ISSUE THREAD

**Issue by HitItAll** [mame82/P4wnP1#159]
Is it possible to add the attack that was used in PoisonTap by Sammy Kamkar? The attack was to inject all unencrypted http requests with a backdoor. 
Thanks.

**Comment by Swiftb0y** [comment]
Well, is already possible with the route spoof option to MITM every connection like the packet squirrel. I'm not sure if the whole poisontap code is released, but if it is, it might work with some minor tweaks.

**Comment by HitItAll** [comment]
Okay, thank you
