### ISSUE TITLE
DuckToolkit

### ISSUE THREAD

**Issue by iamalsaher** [mame82/P4wnP1#170]
**Is it possible to use payloads from the website https://ducktoolkit.com and use it on P4wnP1?** 

I feel it should work but I haven't succeeded in doing so. The provided ducky scripts work perfectly but the one I try to copy or make don't seem to work

**Comment by Swiftb0y** [comment]
It should technically work. There must either be a bug in the generated DuckyScript or in MaMe's custom DuckyScriptEncoder. Could you please post your failing DuckyScript?

**Comment by iamalsaher** [comment]
I will get back to you on this, maybe I am doing some mistake, I am actually new to this, so if it would be a genuine concern I will reply back, till then you can close the issue
