### ISSUE TITLE
Layout İssue

### ISSUE THREAD

**Issue by doggukan** [mame82/P4wnP1#173]
I have tested some payloads but it fails. it types notepadçexe instead of notepad.exe. I have tried "tr" and "us" inside setup.cfg but nothing changed its same .How can i solve this issue ?

**Comment by mame82** [comment]
Change the `lang` parameter in the respective payload, not in `setup.cfg`. For HID backdoor the language is set with `SetKeyboardLanguage`

**Comment by mame82** [comment]
Any progress with the provided hint?
