### ISSUE TITLE
Cannot Establish Wireless Connection with Pi Zero W after Installing P4wnP1

### ISSUE THREAD

**Issue by davidyu96** [mame82/P4wnP1#177]
My wireless network is "unsecured" in that anyone can connect to it, but in order to have access to the internet, you need to register the device's MAC address on the ISP's website. Before installing P4wnP1, I got the wifi to work on the Pi by adding the following to wpa_supplicant.conf:
network={
    ssid="my-ssid"
    key_mgmt=NONE
}
However, after installing P4wnP1, it doesn't seem like the Pi is connected to the internet anymore (ping www.google.com results in: Temporary failure in name resolution). I also have the full Raspbian Stretch OS installed, so when I hop into the GUI and mouse over wifi, it says: "No wireless interfaces found". 
Any help would be appreciated.
Thanks,
David

**Comment by Swiftb0y** [comment]
Could you please provide the output of `sudo journalctl -u P4wnP1.service` and `ifconfig`

**Comment by Anonyvius** [comment]
wich image does you use? Jessie lite or stretch lite? because for stretch you would need:

`country=DE  #omit if US`
`ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev`
`update_config=1`
`network={`
       `ssid="wlan-bezeichnung"`
       `psk="passwort"`
       `key_mgmt=WPA-PSK`
`}`

**Comment by mame82** [comment]
Closed due to missing feedback
