### ISSUE TITLE
Does it work on smartphones

### ISSUE THREAD

**Issue by amohacker** [mame82/P4wnP1#183]
Is it posseble to use it to run duckyscripts on a smartphone?

**Comment by hahnstep** [comment]
yes, one example here  
https://github.com/anbud/DroidDucky

**Comment by amohacker** [comment]
What i meant was can you use the p4wnp1 to execute duckyscripts to(?) phones

**Comment by hahnstep** [comment]
you mean a payload like this ?
https://forums.hak5.org/topic/28165-payload-android-brute-force-4-digit-pin/

**Comment by amohacker** [comment]
Yeah

**Comment by Swiftb0y** [comment]
Im pretty sure it does. Even relative mouse movements should work on android. Wasn't able to test it your myself though. You just need an extra OTG adapter.

**Comment by hahnstep** [comment]
I tested with an Nexus 5 and it dont work, the USB OTG Mode does prevent it.

**Comment by mame82** [comment]
It works against phones. I've done a bunch of experiments with emulating digitizer boards (for absolute cursor positioning), but the phones differ too much. Anyway, MouseScript works very well against Android (except absolute positioning).

Attach an OTG adapter to the phone, connect P4wnP1 like every other USB peripheral and you should be good to go emulating keyboard/mouse.

Tested on Android (7.0), CM 14 against several Samsung devices.


Hid_mouse payload is a good starting point (comments in payload)

**Comment by mame82** [comment]
Sorry, comments are in the MouseScript

https://github.com/mame82/P4wnP1/blob/master/MouseScripts/test.mouse

The payload has yo be modified to disable the keyboard trigger (would be hard to press NUMLOCK frequently  on the Smartphone ;-))

**Comment by amohacker** [comment]
The backdoor didn't trigger on Android 5.1.1 but ill try again maybe i did something wrong

**Comment by mame82** [comment]
The backdoor is Windows only. The client side code is PowerShell/Net based. 
Although the README is a bit outdated, there're enough details on the inner workings of the backdoor, which should clarify that this is Windows only.

P4wnP1 provides the potential to target those devices anyway. Example killchain:
- prepare a backdoored apk (f.e. meterpreter) via http over WiFi
- have a payload handler running on the same WiFi or external server
- prepare a keyboard script, which opens a browser, downloads the apk and confirms the respective dialogs via keystroke injection after joining the WiFi
- conmect P4wnP1 via OTG ro the Android to carry out the keystroke attack
- receive a shell


Be aware of the fact, that I don't provide such payloads for two reasons:
1. My disclaimer
2. They're very device specific when it comes to UI interaction (especially if this should be done using mouse). But there're a few shortcuts common amongst different android versions (including the ones to open a browser or send emails).

Summery:
P4wnP1 could be used against Android if the payload is well prepared, the hid_backdoor is Windows only

**Comment by amohacker** [comment]
I got that the backdoor doesn't work but you should still be able to launch duckyscript's through it right?

**Comment by mame82** [comment]
Yes, the console interface could be used for this ... Same goes for MouseScript with `SendMouseScript`

**Comment by bogiton** [comment]
What about its capability as a network adapter? Could that work under an Android device to create a network between the pi and the phone?
