### ISSUE TITLE
help wanted with a tool 

### ISSUE THREAD

**Issue by hahnstep** [mame82/P4wnP1#185]
Hi 

https://github.com/hahnstep/bunnyscript

i created a tool for easy payload creation everything works fine, except one thing. 
every time if i login i got this error 

-bash: LED: command not found

LED is a shell function from my tool and is sourced by payload and not by P4wnP1 framework !

some body an idea where i can search for this glitch ?

**Comment by Swiftb0y** [comment]
I’m not familiar enough with the fine details of bash and I can’t test it right now but don’t you have to use the `function <name>` keyword to define funktions?

**Comment by hahnstep** [comment]
I found the problem, the payload function "onLogin" is a part of the profile in /tmp/profile 

So everything works fine, dont use bunnyscript functions inside the payload function "onLogin".

thanks
