### ISSUE TITLE
Copy files from machine

### ISSUE THREAD

**Issue by KarlesP** [mame82/P4wnP1#187]
Newbie question but is there a way I can copy files from a machine to P4wnP1?

**Comment by hahnstep** [comment]
yes with scp (ssh)

**Comment by IronPhreak** [comment]
Hi,

There's also the function with the HID Backdoor remote to bring up a shell, change the directory you're viewing then come back out the shell and use "Download [filename]"

**Comment by Anonyvius** [comment]
Yes, and if you have downloaded it you can easily download it from your raspberry with Filezilla or WinSCP to yout Pc/Laptop
