### ISSUE TITLE
Use P4wnP1 on a P3 model B

### ISSUE THREAD

**Issue by babolatom** [mame82/P4wnP1#189]
I follow the same procedure for installing P4wnP1 on a P3 model B but there is no wifi-network created, so can we use P4wnP1 on other model ?

**Comment by Swiftb0y** [comment]
While some features might work on the Pi3B, P4wnP1 is made exclusively for the Pi0 and Pi0W since they are the only Raspi models that are able to act as a USB slave (Keyboard, Mouse, etc.)
