### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by RavelMaurice** [mame82/P4wnP1#190]
Hi mame82, congrats for the wonderful tool. 

I have an issue with my win7 vm. I can't make the to "see" my pi. They identify it as a usb composite device. Is there a workaround about it ?

**Comment by mame82** [comment]
Hard to tell grom here, but I've done it myself and it works.
Set a proper rule to re-route the device to the VM as soon as it gets attached to the host.

If it gets enumerated by the VM host first, things like 'keyboard up' detection could get messed up.
