### ISSUE TITLE
How to upload?

### ISSUE THREAD

**Issue by Anonyvius** [mame82/P4wnP1#194]
Hey, I wanted to upload a file, so i typed : `upload /home/pi/myfile` but i just get the error `File 'myfile' not found!` . So how to upload files and what am i making wrong?
I already triet to type `upload` in the shell but its not working as well.

**Comment by mame82** [comment]
Change directory to the one containing the file with `lcd` from HID backdoor shell before issuing `upload` command.
Alternatively provide a valid absolute path
