### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by ikuamike** [mame82/P4wnP1#204]
error appears after 
Unpacking John the Ripper Jumbo edition...
error: pathspec 'jtr_stretch' did not match any file(s) known to git.

**Comment by Swiftb0y** [comment]
http://p4wnp1.readthedocs.io/en/latest/Troubleshooting/#hid_backdoor-and-hid_frontdoor-are-not-working

**Comment by ikuamike** [comment]
I used --recursive flag, also during cloning it hangs at the end so I use ctrl ^C to stop and checking using 
git checkout -f HEAD
response is
Your branch is up-to-date with 'origin/master'.
but nothing is in the john the ripper folder

**Comment by mame82** [comment]
Yes, you shoul wait

**Comment by ikuamike** [comment]
![screenshot from 2018-02-18 18-53-23](https://user-images.githubusercontent.com/5783614/36354036-6497e036-14df-11e8-941d-2999aed00580.png)

An error occurred during cloning there but it resolved itself and finished okay. 
Installation ended okay as well.
Thanks for the help.
