### ISSUE TITLE
Can't fin p4wnp1 access point

### ISSUE THREAD

**Issue by Victini517** [mame82/P4wnP1#205]
I have the newest release of Raspbian (2017-11-29) and can't see the p4wnp1 network. When i install p4wnp1 i get no errors, but when i choose the hid-backdoor, reboot and plug it into a pc i can't access the pi's network to ssh into it. And when i use iwconfig there is no wlan0 interface. What should i do

**Comment by Swiftb0y** [comment]
Are you sure that you are using a Pi 0 W (emphasis on the W)?
What’s the output of lspci?

**Comment by Victini517** [comment]
I tried that. But on the rpi 0 w pcb it says: Raspberry Pi Zero W v1.1

**Comment by HitItAll** [comment]
Scam?

**Comment by mame82** [comment]
Please use the ready-to-go image provided here https://github.com/mame82/P4wnP1/releases
