### ISSUE TITLE
ERROR HID Backdoor: There is no screen to be detached.

### ISSUE THREAD

**Issue by tomisboy** [mame82/P4wnP1#207]
After testing a bit with the HID Background (in the past everything worked fine)
Somehow the HID Background Payload wont wory any more. 
It started every thing, but windows cannot detect the device and lists it as unnows device

In the ssh client i got the error There is no screen to be detached.

**Comment by HitItAll** [comment]
Just try to launch P4wnP1.py , it is located (I think) in
/P4wnP1/hidtools/backdoor/P4wnP1.py but you may have to search for it
Hope this helps

**Comment by mame82** [comment]
Please refer to the Wiki
