### ISSUE TITLE
[NOT AN ISSUE] Logon Pin Code

### ISSUE THREAD

**Issue by Smavl** [mame82/P4wnP1#208]
Hey, I was wondering if anyone could tell me, if the Windows Lockpicker payload works with the 4-digit pin code, alternatively to the regular password?

**Comment by HitItAll** [comment]
From what I understand, no it does not. P4wnP1 steals the NTLM hash and
cracks that, I'm not sure how/where the pin is stored. Also there have been
patches to fix this bug/vulnerability so unless you have an unpatched
version it wont work at all.
