### ISSUE TITLE
Cannot SSH Into it

### ISSUE THREAD

**Issue by FSEC-DALMASIAN** [mame82/P4wnP1#209]
I have done the install properly and everything has worked with the older P4wnP1 but the newer one does not allow me to ssh. it will open the network and allow me to connect to it but as soon as i try to ssh into it using putty or juicessh it will say something like the server unexpectedly closed and ive reinstalled the p4wnp1 on a fresh micro SD card but still the same error occurs.  

What should i do?

**Comment by mame82** [comment]
Please try the ready-to-go image provided here https://github.com/mame82/P4wnP1/releases
