### ISSUE TITLE
[NOT AN ISSUE] LockPicker executable?

### ISSUE THREAD

**Issue by Six-Six-Zero-One** [mame82/P4wnP1#213]
I made a little shell script for opening the HID Backdoor from the home/ folder, it just points to the P4wnP1/hidtools/backdoor/P4wnP1.py. I've been trying to find a single executable for the Win10 LockPicker for an hour now but I just can't find anything, it doesn't help that I'm kinda new to Linux. Is there an executable? if not, is there a way of running the LockPicker from a single shell script?

Thanks

**Comment by mame82** [comment]
It is a dedicated payload (based on a bash script) in the payloads folder.

I'd like to point out that LockPicker shouldn't work on patched boxes, anymore.

Details are here: https://github.com/mame82/P4wnP1/blob/master/writeup_lockpicker.md
