### ISSUE TITLE
cat: /tmp/dnsmasq.leases: No such file or directory

### ISSUE THREAD

**Issue by ImArtisann** [mame82/P4wnP1#215]
Been getting this error a lot lately on the Pi 0 W tried reinstalling it for the 4th time now dont know what im doing wrong here
![unnamed](https://user-images.githubusercontent.com/37394584/38351647-48fa431a-3865-11e8-94b4-0629685d9703.jpg)

**Comment by mame82** [comment]
Seems to be an issue during installation of dnsmasq. Could you check if the binary is present ?

**Comment by ImArtisann** [comment]
The binary isnt present

**Comment by Swiftb0y** [comment]
I'd try a reinstall and pay close attention for error when running the installer script.

**Comment by ImArtisann** [comment]
What I did to fix this error I ran the line 69 before running ./install.sh
`sudo apt-get -y install dnsmasq git python-pip python-dev screen sqlite3 inotify-tools hostapd autossh bluez bluez-tools bridge-utils ethtool policykit-1 tshark tcpdump iodine`
That seemed to fix the error i was having and it now works

**Comment by mame82** [comment]
Please use the ready-to-go image provided here https://github.com/mame82/P4wnP1/releases

**Comment by piotrek442** [comment]
Thanks to you mame82 it works with ready-to-go image !
I've got the same error "cat: /tmp/dnsmasq.leases"

Yes !
