### ISSUE TITLE
P4wnP1 wont start after first restart.

### ISSUE THREAD

**Issue by Preachton** [mame82/P4wnP1#216]
After installing P4wnP1 on a fresh install of stretch lite on my raspberry pi zero w it wont show a network after restart. after close inspection of the install output i saw some errors but dont know if they affect the network only payload (see picture for errors) Did someone else had this error or does someone know how to fix it?
![p4wnp1 errors](https://user-images.githubusercontent.com/32619404/38442636-37985dc0-39e9-11e8-9342-45ab7d8588ba.png)

**Comment by Preachton** [comment]
(additional note) After restart the leds stop blinking after a few seconds.

**Comment by Swiftb0y** [comment]
> after close inspection of the install output i saw some errors but dont know if they affect the network only payload

I can't tell you how they affect they payload specifically but they shouldnt be there. 
I would try to fix this by getting a clean install of raspbian LITE and do an `sudo apt update && sudo apt upgrade` before running the installer.

**Comment by mame82** [comment]
That's weird `sudo apt-get update` and `sudo apt-get upgrade` are part of install.sh.

@Swiftb0y stated using `apt` instead of `apt-get` works.

This still needs further investigation... have to delay this for about 3 weeks.
Sorry for the inconvenience, I'm rewriting the core scripts currently and have to test  changes on old and new version.

This takes time ... hope the suggestion from @Swiftb0y does the trick, meanwhile

**Comment by Swiftb0y** [comment]
> @Swiftb0y stated using apt instead of apt-get works.

I doesn't make a difference if you use apt or apt-get. I think the issue is that the installer changes some network settings causing the Pi to be unable to connect to the internet.

@Preachton try to replicate the error and send us the complete output of the installer.

**Comment by Preachton** [comment]
after some struggle and sleeping i finally got the network_only payload to work, it had something todo with missing packages propably, it is now fixed and can work with it now hopefully. thanks for the sugestions all
