### ISSUE TITLE
Question Abut the dual mod

### ISSUE THREAD

**Issue by itsStar** [mame82/P4wnP1#218]
Currently i have installed the release build and when connect the power to power socket it didn't work correctly but work well in data socket

So 

Is it possible to run the Pi0W in normal mode via Power socket and not from the data socket after installing the P4wnP1 ?

**Comment by mame82** [comment]
Its intended to work from the data port, as detection of USB device vs host mode is based on this.
Things like WiFi AP should work with a pure power connection, though. But I haven't done much testing on this (will be part of the rework branch, once I have time to work on it).

Hope the image works well otherwise!

**Comment by itsStar** [comment]
Actually the Pi0W is working fine my question was about the Stretch Lite that is not booting in power mod any more

**Comment by mame82** [comment]
It should be booting using power only. If it doesn't boot up, maybe your board is broken.
Things change only on application level (boot scripts behave differently if P4wnP1 isn't used in gadget mode)

**Comment by itsStar** [comment]
About board its not broken because i have checked it with other card and it boot correctly actually it start boot process and turned off while having the P4wnP1 installed on it that's why i asked that if there is a flag to change to boot it in normal mod via power connector :)

**Comment by mame82** [comment]
No, there's nothing like a "disable option". Changes are fixed. I haven't even plans to make it optional (in near future), as I'm still changing the "lower layers" frequently. It would lower development speed even more, if I implement such "usability features", right now - would have to update every time I change something on the core.

Although this isn't the best excuse, I hope you're fine if I close the issue - the question seems answered to me?!

**Comment by itsStar** [comment]
You can close the issue 
Thanks a lot for your time.  :)
