### ISSUE TITLE
Manually start Payload (LockPicker)

### ISSUE THREAD

**Issue by anonymouz4** [mame82/P4wnP1#222]
**Is there any way to start the LockPicker Payload manually?**

> I want to leave my Pi Zero plugged into the machine for a longer time, ssh into the Pi, and then when I want to, start the Hash Grabber.

Any Ideas?

**Comment by mame82** [comment]
There's no support for this. To be honest, what you're realy requesting is USB enumeration on-demand, which is the aim of the rework branch, but I won't change LockPicker, because:
A) Typical usecases have drive-by fashion
B) The issue the payload relied on is fixed

**Comment by anonymouz4** [comment]
Could I then just disable the Payload, plug it in, and when I need it, I enable the payload and reboot?

Is a payload enabled when you save the setup file or after a reboot?

**Comment by Swiftb0y** [comment]
1) No, because the payload has to be run on startup (at least currently, this will probably change in the future). 

2) if you have a patched machine, yes. But some people (especially companies) don't patch regularly.

**Comment by anonymouz4** [comment]
When did Microsoft patch this?

**Comment by mame82** [comment]
https://github.com/mame82/P4wnP1/blob/master/writeup_lockpicker.md
