### ISSUE TITLE
Disable P4wnP1 or use default system wifi setting

### ISSUE THREAD

**Issue by anonymouz4** [mame82/P4wnP1#223]
Before installing P4wnP1, I used the default `/etc/wpa_supplicant/wpa_supplicant.conf` to define the accesspoint it should connect to.
Now that I've installed P4wnP1, nothing works. If I plug in my ethernet adapter, it doesn't use it as connection.
Most of the time I only want to use it via Ethernet cable as VPN server and I don't want to install and uninstall P4wnP1 every time I use it.

Is there a way to disable P4wnP1 temporarily or to enable ethernet cable?

**Comment by anonymouz4** [comment]
I've done many changes, so I can't just use a fresh sd, like DynDns and so on. To get all of those things working takes a lot of time so a solution to enable ethernet or to uninstall P4wnP1 would be better

**Comment by mame82** [comment]
@anonymouz4
If you'd like to bring up a ethernet based OpenVPN endpoint, there're solutions for this. But P4wnP1's goal is a different one. 
I suggest using a proper distro for that.

Thanks @Swiftb0y for trying to help in this, anyway.

I'm closing this issue, as it hasn't any relation to this project or features provided by it, nor could I spot a real issue with the project in this conversation.

**Comment by Swiftb0y** [comment]
Note: even permanently uninstalling P4wnp1 is difficult. So if you want your VPN server to be stable, reinstall raspbian and setup the VPN again.

**Comment by mame82** [comment]
As already pointed out:
Different usecase, different sdcard.
That's why the PCB provides SD instead of fixed flash

**Comment by anonymouz4** [comment]
@mame82 It would be nice if you could add in the ReadMe File that you cam't uninstall, once installed?

**Comment by anonymouz4** [comment]
My idea was to get both things working on one sd. Also everything else exept the ethernet part is working so I thought there might be a workaround for this.

**Comment by Swiftb0y** [comment]
Again, even if you can find a magic workaround, it probably won't be reliable at all.
