### ISSUE TITLE
Changing the wifi-ssid has no effect

### ISSUE THREAD

**Issue by MoranDada** [mame82/P4wnP1#234]
I have changed the WIFI_ACCESSPOINT_NAME and WIFI-ACCESSPOINT_PSK in the setup.cfg，but when I reboot it,the wifi information was not changed ，I have tried it several times,but nothing changed.

**Comment by Swiftb0y** [comment]
Please have a look at the official wiki: https://p4wnp1.readthedocs.io/en/latest/Troubleshooting/#my-settings-in-setupcfg-are-not-used-by-the-payload
