### ISSUE TITLE
i Have a three position switch and a usb case for my P4wnP1

### ISSUE THREAD

**Issue by FSEC-DALMASIAN** [mame82/P4wnP1#242]
NOT AN ISSUE
I Have a three position switch and a usb case for my P4wnP1, how can i program it to swap the config.cfg file in the p4wnp1 folder for switchable payloads?
if anyone can help me that would be awesome

i've also added an bright blue led to gpio 6 to replace the act led which helps a lot when you have a case.

**Comment by hahnstep** [comment]
Hi. you can solve this via script. 
give a look this two lines **# comment out active payload** and   **# activate payload** 
http://stephanhahn.ch/posts/p4wnp1-oled-bonnet-mod/
i hope its helps

**Comment by 3FF-53C-Member-DalmAsian** [comment]
hey i read most of it but i just don't get it
