### ISSUE TITLE
P4wnP1 shell not showing when connecting

### ISSUE THREAD

**Issue by Swiftb0y** [mame82/P4wnP1#29]
^^

Help xD
Also it seems like john the ripper failed to install, but that isnt a problem since I dont plan to use responder.

**Comment by mame82** [comment]
JtR only downloads and extracts... sure you cloned recursively?

**Comment by Swiftb0y** [comment]
no....
Can I just clone again or do I have to reinstall raspbian?

**Comment by mame82** [comment]
You should run `install.sh` again, after cloning a second time. Reinstall of raspbian shouldn't be needed

**Comment by Swiftb0y** [comment]
ok thanks
