### ISSUE TITLE
hid_keyboard.txt and wifi not working

### ISSUE THREAD

**Issue by daankent** [mame82/P4wnP1#293]
Hello,
I installed P4wnP1 succesfully, and i selected the hid_keyboard.txt. And i put this code into the onbootup section:cat <<- EOF | duckhid
		DELAY 3000
GUI R
DELAY 500
STRING iexplore -k http://fakeupdate.net/win10u/index.html
ENTER
EOF 

But when i plug the pi zero w into a windows 10 computer nothing happend. The keyboard is set to us because that's the keyboard language i use. And also when i plug the pi zero w in the wifi to ssh does not show up, so i can't change the payload.
Can someone help me solve this problem

**Comment by Swiftb0y** [comment]
This project is deprecated by [P4wnP1 A.L.O.A](https://github.com/mame82/P4wnP1_aloa). Please head over there and take a look at HIDScript.
