### ISSUE TITLE
P4wnP1 doesnt work 

### ISSUE THREAD

**Issue by Te0d0r** [mame82/P4wnP1#297]
hello, I am trying to make a backdoor using P4wnP1, but then when I reload the pi zero, it just shows the regular terminal, I reinstalled it a few times already and it still doesn't work. please help

**Comment by Te0d0r** [comment]
my problem is really similar to the one gonebad1222 (#110  ) had, but I couldn't find the solution to my problem there

**Comment by Te0d0r** [comment]
it was an sd card problem

**Comment by 1byeworld** [comment]
what did you do to resolve the problem because in facing the same issue and tried many different things such as changing cables, sd cards
