### ISSUE TITLE
./install.sh

### ISSUE THREAD

**Issue by kg04ls** [mame82/P4wnP1#313]
I print ./install.sh , and pi return :
Testing Internet connection and name resolution...
...[pass] Internet connection works
Testing if the system runs Raspbian Jessie or Stretch...
...[Error] Pi is not running Raspbian Jessie or Stretch! Exiting ...
Help me plz 
I use firmware from the site https://p4wnp1.readthedocs.io/en/latest/

**Comment by megah3rtz** [comment]
@Jora73 What version of raspian have you installed?

**Comment by DarthAluminium** [comment]
You need to install previous version of Raspbian. From the download page of Raspbian you can only download Buster, but you need Raspbian Stretch or Raspbian Jessie.

There is you can download all Raspbian versions:
https://downloads.raspberrypi.org/raspbian/images/

So I downloaded and installed last Raspbian Stretch and P4wnP1 was successfully installed.
https://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/

**Comment by fortworthless** [comment]
**@DarthAluminium**, thank you. I spent a day of insanity trying to make buster work, then Kali, and on and on. I looked everywhere for that old raspbian image. I even edited the install.sh to not check the version. And now I have it, finally at 2am. 

**But I didn't give up and it works!**
![http://www.sta-hi.com](https://user-images.githubusercontent.com/9684626/71956505-6156a300-31b9-11ea-9661-bc95e1a2385c.jpg)
