### ISSUE TITLE
[Error] Pi is not running Raspbian Jessie or Stretch! Exiting ...

### ISSUE THREAD

**Issue by DarthAluminium** [mame82/P4wnP1#326]
pi@raspberrypi:~/P4wnP1 $ ./install.sh
Testing Internet connection and name resolution...
...[pass] Internet connection works
Testing if the system runs Raspbian Jessie or Stretch...
...[Error] Pi is not running Raspbian Jessie or Stretch! Exiting ...

What should I do to solve this error?

**Comment by saintofinternet** [comment]
did you find a solution for the issue?

i am facing the same " Pi is not running Raspbian Jessie or Stretch " and i have downloaded the latest Raspbian Buster Lite ( Minimal image based on Debian Buster )

**Comment by DarthAluminium** [comment]
You need to install previous version of Raspbian. From the download page of Raspbian you can only download Buster, but you need Raspbian Stretch or Raspbian Jessie.

There is you can download all Raspbian versions:
https://downloads.raspberrypi.org/raspbian/images/

So I downloaded and installed last Raspbian Stretch and P4wnP1 was successfully installed.
https://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/
