### ISSUE TITLE
FireStage1 and SetKeyboardLanguage

### ISSUE THREAD

**Issue by TilGP** [mame82/P4wnP1#331]
Does anybody know what I did wron or did Microsoft close the Backdoor?
[Picture](https://drive.google.com/open?id=1KJRlPA6gMBrbpUZ19_hBH-u6UrQJ2TKT)
And sry that i couldn't make a screenshot... and

**Comment by Jorismalik** [comment]
exit

**Comment by Jorismalik** [comment]
or STRG and C

**Comment by TilGP** [comment]
no! I don't mean "How to close the Backdoor". I mean if Microsoft colsed the Backdoor.
And I found out, that it workes, when you add "nohide" after FireStage1, but if you do that it's not stealthy.

**Comment by Jorismalik** [comment]
I think u reboot and its gone

**Comment by TilGP** [comment]
nvm
