### ISSUE TITLE
Where is the Code for the Web Interface?

### ISSUE THREAD

**Issue by spaceman5** [mame82/P4wnP1#336]
Hi

This is not really an issue, but just a small question by me..

I really like the Web Interface of P4wnPi.
I would like to look at the code for it, but when going over the folders and some files of the repository, for some reason I could not find it..
(I am talking about regular P4wnP1, not the newer ALOA version)

Can anyone please direct me to the relevant files?

Thank you very much

**Comment by DonaldDucker34** [comment]
The Original Pwnpi has no WebInterface?

**Comment by spaceman5** [comment]
It does have.
I am just looking for the code that is responsible, and cannot find it..
