### ISSUE TITLE
Unable to set German Keyboard Layout

### ISSUE THREAD

**Issue by felbinger** [mame82/P4wnP1#39]
Hello,
I am unable to set the German keyboard layout. I tried it with `SetKeyboardLanguage de`. If I type `SetKeyboardLanguage`, 
I see that it are bracketed arround it: `[2:de]`

I guess that this feature will be implemented soon, right? Can I help? Tell me what is to do that the feature get implemented and I try to help. I am not the best programmer but I will give my best.

Best regards
Nico Felbinger

**Comment by mame82** [comment]
It is implemented and tested. In fact I'm using de keyboard layout myself. Is duckencoder.py installed correctly  (cloned recursively) ?

**Comment by felbinger** [comment]
Okay, I installed it again on a fresh Raspbian installation and its working now.
