### ISSUE TITLE
OrangePi Zero & NanoPi NEO Air

### ISSUE THREAD

**Issue by minkione** [mame82/P4wnP1#4]
Did Anyone tried it with those boards?
Due to difficulty to find in-stock RPi  Zero, should not better to port to those devices as well?

**Comment by mame82** [comment]
AS I don't own these devices, I'm not able to test it. But basically these things are beeded:
- an UDC (universal device controller)
- a kernel compiled with USB gadget capabilities
- gadget configuration via configfs
- the UDC has to provide enough EPs to run all composite functions in parallel (I think the UDC of PiZero provides 8)
- WLAN /  Bluetooth capabilities for upcoming features (airgap bridge)
