### ISSUE TITLE
network only payload

### ISSUE THREAD

**Issue by THE4W350M3R00T** [mame82/P4wnP1#40]
Hey after playing a bit around with P4wnP1 hid backdoor i changed the payload back too network only and now i won't get a wlan hotspot anymore i tried to change it back to hid backdoor but that didn't help either could anybody help me pls?

EDIT: It keeps getting more weird i now don't even have the USB over ethernet thingy anymore

**Comment by mame82** [comment]
Yes, sounds weird. What is the HDMI output at boot?

**Comment by THE4W350M3R00T** [comment]
That it started the server and everything is running fine

**Comment by mame82** [comment]
Good to hear
