### ISSUE TITLE
There is no screen to be detached -HID Backdoor

### ISSUE THREAD

**Issue by jgbuddy** [mame82/P4wnP1#41]
this is a great project thanks for all the hard work and dedication mame82.

I'm also getting the same "there is no screen to be detached" error, even after trying multiple cables. If I run ~\P4wnPi1-master\hidtools\backdoor\P4wnP1.py, i get :

File "P4wnP1.py", line 13, in <module>
    from DuckEncoder import DuckEncoder 
ImportError: No module named DuckEncoder

This is probably some stupid mistake on my part as i am new to this stuff, but any help would be much appreciated! Thanks!

**Comment by mame82** [comment]
Sounds like you didn't cloned recursively and are missing duckencoder.py

**Comment by jgbuddy** [comment]
ok, googled it and everything makes sense now. thanks

**Comment by mame82** [comment]
No need to use google, everything is here https://github.com/mame82/P4wnP1/blob/master/INSTALL.md

;-)
