### ISSUE TITLE
Too fast firing stage1

### ISSUE THREAD

**Issue by gloglas** [mame82/P4wnP1#47]
I have a issue 3 out of 1 commands FireStage1 results on my win7 machine to run not completed code. Add please delay option to setup.cfg

**Comment by Swiftb0y** [comment]
Do you mean the keystrokes come to fast or to soon?

**Comment by mame82** [comment]
Run `help FireStage1`  to see how to solve your problem ;-)

**Comment by Puffball101961** [comment]
I have a similar issue, when I execute `FireStage1` it opens a run box, enters powershell.exe and stays on that for a couple seconds, then all of the code gets types in the box.
Plz Help!
