### ISSUE TITLE
SetKeyboardLanguage be

### ISSUE THREAD

**Issue by Skrychi** [mame82/P4wnP1#49]
Setting this keyboard layout crashes the interface and shoves you straight to the terminal. I haven't checked other layouts, but so far i've tested fr, de, us, gb, and es. So its possible that other layouts are affected?
I've tried reformatting and started from scratch multiple times with the same result.
Please fix :')

**Comment by mame82** [comment]
I'll investigate this, but I'm afraid I'm not able to work on this the next two weeks.
So please be patient (filed as bug already).

**Comment by julienlemonde** [comment]
To add to the bug, same behavior for ca.

**Comment by mame82** [comment]
@julienlemonde  @Skrychi 

ca, be, ru and no had errors, which are hopefully fixed in latest release.

Could you confirm

**Comment by Skrychi** [comment]
So far, sending ducky scripts work fine.
Here's what I get when I trigger FireStage1
As you can see bottom right i've tested it on all 3 be layouts.
http://imgur.com/a/yoVMc
![setkeyboardlanguage be error](https://user-images.githubusercontent.com/31053995/29718616-47d84ab8-89ab-11e7-86d1-d083607b2ae5.png)

**Comment by mame82** [comment]
`[` and `]` are excchanged...so still an issue in be.properties

**Comment by julienlemonde** [comment]
Ca is working now, Thanks!

**Comment by mame82** [comment]
@Skrychi 

BE layout should be working now (tested with `FireStage1`)

**Comment by Skrychi** [comment]
Fixed. As for the others, Someone will have to confirm.

**Comment by MaximusBaton** [comment]
sorry for reopening this issue, however I'm facing the same problem.
the victim's default windows language is 'ru'. so the FireStage just types ru symbols in powershell window.
changing the language to us with SetKeyboardLanguage perform an app crash like the topic started had described.
u have any clue for this?
