### ISSUE TITLE
No screen to be detached

### ISSUE THREAD

**Issue by asing012** [mame82/P4wnP1#53]
Payload - hidbackdoor
Target OS - Windows 7

I read the other two tickets about this same issue and I tried everything but i am still getting no screen to be detached error. Keyboard driver seems to be installed in the target OS and I am able to run the P4wnP1.py using python command. But when I type FireStage1 it's not doing anything.

**Comment by mame82** [comment]
Please chech the content of the `duckencoder` folder. Are there any files ?

**Comment by asing012** [comment]
It has the duckcoder.py README.md and resources folder.

**Comment by mame82** [comment]
Okay, no problem with encoder.
Why do you have to start `P4wnP1.py` manually, is there an error on boot (HDMI out).

Please also check the output of `ls -la /dev/hidg*`.
Make sure `hid_backdoor.txt` payload is selected, first.

**Comment by asing012** [comment]
I found the issue, It was the cable. It is working now..
Thank You

**Comment by mame82** [comment]
Nice to hear

**Comment by TeCoEd** [comment]
My issue was the cable too, tried a USB Stem and did not work, went back to old data cable and worked fine

**Comment by mame82** [comment]
Added a USB Stem right now and it works like charm for me

https://twitter.com/mame82/status/911879277230075904

**Comment by TeCoEd** [comment]
Odd as this is the exact same one I used, must be my poor soldering skills!
Program has 'screen detached' error run on USB stem, but use cable and it works fine!
