### ISSUE TITLE
[NotAnIssue] Can it safe the Keyboardlanguage?

### ISSUE THREAD

**Issue by Anonyvius** [mame82/P4wnP1#57]
Can i safe the Kexboardlanguage or have i to set it every time i boot the raspberry up?

**Comment by mame82** [comment]
The keyboard language for the backdoor be changed persistently in rhis file:

https://github.com/mame82/P4wnP1/blob/master/hidtools/backdoor/config.txt#L8

**Comment by Anonyvius** [comment]
Okay thank you. Und du sprichst doch deutsch oder? wenn ja danke für die schnelle antwort

**Comment by mame82** [comment]
Kein problem, aber Englisch dürfte für den Rest hilfreicher sein ;-)
