### ISSUE TITLE
 How to reconnect to the Internet via Wifi (zero W)

### ISSUE THREAD

**Issue by MJGames** [mame82/P4wnP1#65]
Hi,
my Question is: How can i reconnect to the Internet via Wifi?

**Comment by 3FF-53C-Member-DalmAsian** [comment]
https://youtu.be/QEWaIoal5qU

**Comment by Swiftb0y** [comment]
Ive Opened a PR for this functionality but its isnt merged yet....

**Comment by mame82** [comment]
@swiftboy
Commented on PR

**Comment by mame82** [comment]
@MJGames connecting to existing WiFis will only be possible in future versions of P4wnP1
