### ISSUE TITLE
Some issue with the hid

### ISSUE THREAD

**Issue by rogafe** [mame82/P4wnP1#68]
Hello everyone, 
I have tried some of my own Ducky payload on the hid_backdoor.
But when i try to run it with an payload like [this](https://gist.github.com/rogafe/af681a4e3f5debaa33804dbc8609c8eb)
I don't know what I have did wrong

**Comment by jcstill** [comment]
Just put your ducky script into the `DuckyScripts` folder and then start the server with `sudo python /home/pi/P4wnP1/hidtools/backdoor/P4wnP1.py`. Then use `SendDuckyScript` and pick the one you want.

**Comment by mame82** [comment]
Replace `outduck` with `duckhid`.

**Comment by mame82** [comment]
@rogafe Problem solved?

**Comment by rogafe** [comment]
Yes sorry I forgot about that issue
