### ISSUE TITLE
Possibility of downloadable IMG

### ISSUE THREAD

**Issue by bytedeez** [mame82/P4wnP1#7]
Hi I am having tons of issues setting up rdnis as well as with wpa_supplicant via alternative method of gaining IC.

Anyway you could upload a downloadable img?
Thanks in advance.

**Comment by mame82** [comment]
Unfortunately not possible at the moment. All Images I'm currently using include custom development code and aren't production ready.

I consider uploading a ready-to-go image, when devel branch is merged into master, but this takes time.

Sorry!
Maybe somebody else could help out. I'll leave the issue open for some days.

**Comment by bytedeez** [comment]
Okay thank you. I'm sure I will eventually figure out my issues with setting up the pi zero as a USB dongle as well as the wpa_supplicant error. 
Might try an older version of raspbian from 03/02/2017. 
Correct me if I'm wrong but the kernel must be 4.4 or above right?

**Comment by mame82** [comment]
Working Kernel is 4.4.50+

When Raspbian moves to the next Kernel, real issues could arise, but this isn't the case at the moment.

https://github.com/raspberrypi/linux/issues/1943#issuecomment-290928266

**Comment by bytedeez** [comment]
Okay thanks you!
You are doing really awesome work here, can't wait til I can try it out for myself, until then keep it up!
I am going to close this for now.
