### ISSUE TITLE
[Informative]Until strech is supported

### ISSUE THREAD

**Issue by amohacker** [mame82/P4wnP1#72]
Hey until raspbian strech is supported this is how you can get and succesfully install a raspbian jessie image.
-First go ahead and download the last raspbian version from their archive (the zip file) http://downloads.raspberrypi.org/raspbian/images/raspbian-2017-07-05/
-After you have downloaded it unzip the file with 7zip.
-Next use download etcher from https://etcher.io/ and image it with this, pretty much any other software will fail to create a working image.
-After it finished add a blank file called ssh to boot and edit cmdline.txt and add `modules-load=dwc2,g_ether` after rootwait sepperating it with a space on each side
-edit config.txt with notepad++ and a line with `dtoverlay=dwc2` at the end.

-eject the micro sd card and you should be good to go!

Hope i helped somebody out with this.

**Comment by mame82** [comment]
Stretch support added to installer ;-)
