### ISSUE TITLE
I can't turn off the blinking

### ISSUE THREAD

**Issue by Doppelmord** [mame82/P4wnP1#79]
So, this is one of the more stupid things I ever did.
Basicly I ran the LED script that makes the LED blink (Kind of a giveaway really).
And now I can't get it to stop blinking... Is it supposed to do that? If not how do I stop it?
It's not a big deal buts it's driving me crazy over time...

Thanks in advance :)

**Comment by mame82** [comment]
> Basicly I ran the LED script that makes the LED blink (Kind of a giveaway really)

Could you give more details on this?

**Comment by mame82** [comment]
@Doppelmord please re-open the issue if the problem isn't solved neanwhile
