### ISSUE TITLE
Raspberry Zero W SSH over wifi

### ISSUE THREAD

**Issue by robbiebobbie** [mame82/P4wnP1#8]
hey awesome project.
I'm not that familiar with linux but is it possible to ssh into a Zero W over Wifi?
After the setup it still connects to my router but i cant login.

**Comment by mame82** [comment]
I start implementing WiFi capabilities after HID covert channel is done.
For now SSH server is running on all interfaces and should be reachable if WLAN is connected. As DHCP client is disabled, you have to manually setup Pi's wlan interface. 

So right now, no further support on this...as stated in readme. Sorry.

Feel free to ping back when WiFi is on the feature list of master branch and I'll try to help out
