### ISSUE TITLE
Can't connect to pi after Payload initiated

### ISSUE THREAD

**Issue by r00t1000** [mame82/P4wnP1#81]
Unfortunately, I have a persisting problem of the Pi immediately executing the payload then not being able to be connected to via SSH. It usually did this on my Windows pc, but recently it has begun asking my Mac if I have a keyboard attached but won't be recognized anymore.

**Comment by thebeastgamer25** [comment]
@mame82

**Comment by mame82** [comment]
Does the problem still exist on latest master branch commit ?
