### ISSUE TITLE
Download tools on P4wnP1

### ISSUE THREAD

**Issue by Hugand** [mame82/P4wnP1#85]
Hi everyone! So, I recently installed P4wnP1 on my RPi0w and I need to download some tools to the pi, but since it uses his own network and can't use the internet normally I can't get them. How can I solve this??

**Comment by mame82** [comment]
Happy to have a new user, help is on the way...
Here: https://youtu.be/QEWaIoal5qU

**Comment by Hugand** [comment]
Thank you so much! Is it possible to use the RPi as HID and at the same time as a mass storage device?
Nice job on the P4wnP1 btw!

**Comment by mame82** [comment]
Yes, hakin9_tutorial payload is an example on this

**Comment by Hugand** [comment]
Ok, thanks a lot!

**Comment by Hugand** [comment]
Oh, one more thing, how can I run a ducky payload instead of the default payloads like /payload/hid_keyboard.txt??

**Comment by mame82** [comment]
Same answer, hakin9_tutorial shows how to use a DuckyScript payload

**Comment by Hugand** [comment]
ok, thanks once again
