### ISSUE TITLE
How to change Access Point name and password?

### ISSUE THREAD

**Issue by g33xter** [mame82/P4wnP1#98]
Hey, I recently started working with P4wnP1. I was wondering how to change default AP and Password? I tired from /tmp/hostapd.conf but, the moment I restart the device it switch back to default creds.

**Comment by e3net** [comment]
Edit file `setup.cfg`

```
WIFI_ACCESSPOINT_NAME="your_name_wifi"
WIFI_ACCESSPOINT_PSK="your_pass_to_wifi"
```

**Comment by mame82** [comment]
Change the option hinted by @e3net in the respective payload or remove them from the payload entirely, to use ones from setup.cfg

**Comment by g33xter** [comment]
Gotcha. Thanks.
